export const DATABASE_URL = process.env.DATABASE_URL;
export const JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;
export const FRONTEND_BASE_URL = process.env.FRONTEND_BASE_URL;

export const KHALTI_LIVE_SECRET_KEY = process.env.KHALTI_LIVE_SECRET_KEY;
export const KHALTI_LIVE_pUBLIC_KEY = process.env.KHALTI_LIVE_PUBLIC_KEY;
export const KHALTI_PAYMENT_VERIFICATION_URL = process.env.KHALTI_PAYMENT_VERIFICATION_URL;
export const KHALTI_PAYMENT_INITIATION_URL = process.env.KHALTI_PAYMENT_INITIATION_URL;

export const ESEWA_MERCHANT_CODE = process.env.ESEWA_MERCHANT_CODE;
export const ESEWA_SECRET_KEY = process.env.ESEWA_SECRET_KEY;
export const ESEWA_PAYMENT_INITIATION_URL = process.env.ESEWA_PAYMENT_INITIATION_URL;
export const ESEWA_PAYMENT_VERIFICATION_URL = process.env.ESEWA_PAYMENT_VERIFICATION_URL;